# Generated by Django 2.2.7 on 2020-01-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url_id', models.PositiveIntegerField()),
                ('step', models.SmallIntegerField()),
                ('calory', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
